# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  directory-input:  # id of input
    description: 'directory location input'
    required: true
    default: '/dist'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.directory-input}}
    - ls -la /usr/src/app/
    - --volume ${{inputs.directory-input}}:/usr/src/app/${{inputs.directory-input}}
