# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  directory-input:  # id of input
    description: 'directory location input'
    required: true
    default: '/dist'
runs:
  using: 'docker'
  image: 'Dockerfile'
  options: -v dist/:/usr/src/app/dist
  args:
    - ${{ inputs.directory-input}}
