name: 'Upload Provider'
description: 'Uploads custom terraform provider to private registry in tf cloud'
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        FUN_SECRET_YAY: ${{secrets.FUN_SECRET}}
      run: echo FUN_SECRET_YAY
