# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  directory-input:  # id of input
    description: 'directory location input'
    required: true
    default: '/dist'
runs:
  using: 'docker'
  image: 'Dockerfile'
  options: -v /home/runner/work/action-build-example-app/action-build-example-app/${{ inputs.directory-input}}:/usr/src/app/${{ inputs.directory-input}}
  args:
    - ${{ inputs.directory-input}}
    - ls -la /usr/src/app/
